# Generated by Django 5.0.6 on 2024-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='url',
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='author/'),
        ),
    ]
